[package]
name = "rust-euler"
version = "0.1.0"
authors = ["Jeff Schwab <jeff@unbuggy.com>"]

[dependencies]

[features]
slow_tests = []

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "my_benchmark"
harness = false
